#!/bin/bash

DEFAULT_IHOME=`pwd`
DEFAULT_IDD=${DEFAULT_IHOME}/data

if [ -f config/improve.env ] 
then
    echo Config exists, please remove config/improve.env
    exit 
else
    echo Creating config file
    cat  << EOF > config/improve.env
export IHOME=${DEFAULT_IHOME}
export IDD=${DEFAULT_IDD}
export IMPROVE_DATA_DIR=\${IDD}
EOF

mkdir -p $DEFAULT_IDD
echo Setting IHOME to current directory. Please modify config/improve.env to change locations.

fi

